#!/usr/bin/env bash
# vault-init/init.sh — Idempotent vault initialization.
# Creates all directories and copies templates without overwriting existing files.
# Usage: bash init.sh [vault-path]
#
# If no path is given, uses $AGENT_VAULT.
set -euo pipefail

vault="${1:-${AGENT_VAULT:-}}"
if [[ -z "$vault" ]]; then
	echo "Error: No vault path provided and AGENT_VAULT is not set." >&2
	echo "Usage: bash init.sh <vault-path>" >&2
	exit 1
fi
# Expand leading tilde so paths like ~/foo work correctly
vault="${vault/#\~/$HOME}"

skill_dir="$(cd "$(dirname "$0")" && pwd)"
created=0

# Helper: create directory if missing
ensure_dir() {
	if [[ ! -d "$1" ]]; then
		mkdir -p "$1"
		echo "  created: $1"
		((created++)) || true
	fi
}

# Helper: copy file if missing (no overwrite)
ensure_file() {
	local src="$1" dst="$2"
	if [[ ! -f "$dst" ]]; then
		mkdir -p "$(dirname "$dst")"
		cp "$src" "$dst"
		echo "  created: $dst"
		((created++)) || true
	fi
}

echo "Initializing vault at: $vault"
echo ""

# Create directory structure
ensure_dir "$vault/tasks"
ensure_dir "$vault/_misc/archive/tasks"
ensure_dir "$vault/audits"
ensure_dir "$vault/projects"
ensure_dir "$vault/_misc/cache"
ensure_dir "$vault/design"
ensure_dir "$vault/draft"
ensure_dir "$vault/repo-notes"
ensure_dir "$vault/_misc/templates"
ensure_dir "$vault/_misc/images"

# Copy templates (only if missing)
if [[ -d "$skill_dir/templates" ]]; then
	for tmpl in "$skill_dir/templates"/*.md; do
		[[ -f "$tmpl" ]] || continue
		ensure_file "$tmpl" "$vault/_misc/templates/$(basename "$tmpl")"
	done
fi

# Write AGENTS.md (only if missing)
if [[ ! -f "$vault/AGENTS.md" ]]; then
	cat >"$vault/AGENTS.md" <<'AGENTS_EOF'
# Agent Vault

## What This Repository Is

This is a **git-tracked Obsidian vault** serving as a knowledge base. It contains
reference documentation, implementation schemas, code reviews, and triage
entries — not source code. There are no build systems, tests, or linters.

## Vault Structure

### `tasks/<owner>/<repo>/<task>/` — Implementation tasks

Each task directory contains up to three files:
- `schema.md` — Actionable implementation spec that an AI agent can execute step-by-step.
- `review.md` — Structured code review for work done against the schema.
- `triage.md` — Escalation notes, design questions, and run summaries.

### `tasks/_fleet/<task>.md` — Fleet (cross-repo) schemas

Umbrella documents coordinating work across multiple repositories. These are
flat files (not directories) since they don't have per-task reviews or triage.

### `repo-notes/<owner>/<repo>/` — Repository reference documentation

Reference summaries of repository internals (build systems, architecture,
scripts). A future agent session should be able to understand a subsystem
by reading one file.

### `design/` — Design documents

High-level thinking: architecture explorations, trade-off analyses, roadmaps,
and cross-cutting concerns.

### `draft/` — Work-in-progress documents

Staging area for notes and specs under active development.

### `_misc/` — Infrastructure (hidden by `_` prefix in Obsidian)

Umbrella directory for all vault infrastructure that is not user-facing content.
Collapsed by default in the Obsidian file explorer. Contains:

- `_misc/archive/` — Completed work
- `_misc/cache/` — GitHub metadata cache
- `_misc/templates/` — Format templates
- `_misc/images/` — Notification icons and image assets

#### `_misc/archive/` — Completed work

Mirrors the active directories for work that has been completed:
- `_misc/archive/tasks/` — Completed task directories (schema + review + triage).

When asked to archive tasks, move them from the active directory into the
corresponding `_misc/archive/` subdirectory.

### `audits/<owner>/<repo>/` — Audit reports

Point-in-time quality snapshots generated by `@auto-auditor`. Each file is
named `<date>-<label>.md` (e.g. `2026-03-29-full-audit.md`). Multiple audits
per repo accumulate here as a historical series.

#### `_misc/cache/` — GitHub metadata cache

Cached project board, milestone, and label data for repositories.

### `projects/<owner>/` — Project status documents

Human-readable per-repo project snapshots maintained by `@project-manager`.
Each file (`projects/<owner>/<repo>.md`) mirrors the current state of open/closed
issues, milestone progress, and project board columns for a vault-managed repo.
Refreshed whenever PM performs state-changing operations or is explicitly asked
to sync. Use `backend: github` for GitHub-backed projects and `backend: local`
for vault-only tracking.

### Other

- `.obsidian/` — Obsidian configuration (do not modify).
- `AGENTS.md` — This file.
- `triage-inbox.md` — Generated triage dashboard (run `vault-triage` skill to refresh).
- `_misc/templates/` — Format templates for schemas, reviews, triage, and issues.
- `_misc/images/` — Notification icons and other image assets.

## Workflow

All non-trivial implementation work follows three phases:

1. **Plan** — `@planner` explores the codebase, discusses with the user, writes
   a schema to `tasks/<owner>/<repo>/<task>/schema.md`.
2. **Implement** — `@implementor` or `@auto-implementor` executes the schema
   step-by-step, committing after each group.
3. **Review** — `@reviewer` writes a structured review to
   `tasks/<owner>/<repo>/<task>/review.md`.

## Agent Roles

| Agent | Role |
|-------|------|
| `@planner` | Schema authoring, GitHub issue creation |
| `@project-manager` | Issue lifecycle, project board ops, milestone management, vault project status |
| `@implementor` | Manual schema execution with approval gates |
| `@auto-implementor` | Autonomous schema execution with bounded review loop |
| `@reviewer` | Structured code review |
| `@designer` | Repo notes, design documents, drafts |
| `@auto-auditor` | Headless audit agent — tool detection, static analysis, vault report |

## Environment

| Variable | Purpose |
|----------|---------|
| `AGENT_VAULT` | Path to this vault (e.g. `~/obsidian/agent.obs`) |
| `AGENT_REPOS` | Path to local repository checkouts (e.g. `~/repos`) |

## Conventions

- Documents are Markdown, authored for Obsidian (may use wiki-links, callouts).
- Do not hard-wrap prose — Obsidian soft-wraps paragraphs.
- Schemas and reviews use YAML frontmatter for metadata (`repo`, `status`, `date`, etc.).
- Path convention: `tasks/<owner>/<repo>/` mirrors the local checkout path
  convention `~/repos/<owner>/<repo>`.
- Use the `obsidian` CLI for vault file management (move, delete, create, properties).
- **Task and issue titles must not contain regex special characters** (`.`, `(`, `)`,
  `*`, `[`, `]`, `+`, `?`, `{`, `}`, `^`, `$`, `|`, `\`). The `vault-lint` script
  uses title text as a regex pattern when scanning review files — special characters
  will silently corrupt issue-block extraction.

## Obsidian CLI

The `obsidian` command is available for headless vault management:

```bash
# Read operations
obsidian files vault=agent.obs           # List all files
obsidian folders vault=agent.obs         # List all folders
obsidian read vault=agent.obs path="<p>" # Read file contents
obsidian search vault=agent.obs query="<q>"  # Search vault
obsidian property:read vault=agent.obs path="<p>" name=<prop>  # Read property

# Mutation operations
obsidian move vault=agent.obs path="<old>" to="<new>"         # Move (updates links)
obsidian delete vault=agent.obs path="<p>" permanent           # Delete
obsidian create vault=agent.obs path="<p>" content="<text>"    # Create
obsidian property:set vault=agent.obs path="<p>" name=<prop> value=<val>  # Set property
```
AGENTS_EOF
	echo "  created: $vault/AGENTS.md"
	((created++)) || true
fi

echo ""
if ((created > 0)); then
	echo "Done: $created items created."
else
	echo "Done: vault already fully initialized."
fi
echo "Vault path: $vault"
