#!/usr/bin/env bash
# vault-triage/setup.sh — One-time notification setup.
# Detects platform, generates ntfy topic, configures client and timers.
# Usage: bash setup.sh
#
# Requires: AGENT_VAULT set in environment
# No sudo required.
set -euo pipefail

vault="${AGENT_VAULT:?AGENT_VAULT is not set}"
skill_dir="$(cd "$(dirname "$0")" && pwd)"

# ── Platform detection ──────────────────────────────────────────────
detect_platform() {
	if [[ "$(uname -s)" == "Darwin" ]]; then
		echo "macos"
	elif [[ -f /proc/version ]] && grep -qi "microsoft" /proc/version; then
		if systemctl --user is-system-running 2>/dev/null | grep -qE "^(running|degraded)$"; then
			echo "wsl-systemd"
		else
			echo "wsl"
		fi
	else
		echo "linux"
	fi
}

platform="$(detect_platform)"
echo "Detected platform: $platform"

# ── Topic generation ────────────────────────────────────────────────
topic_file="$vault/_misc/cache/ntfy-topic.txt"
mkdir -p "$vault/_misc/cache"

if [[ -f "$topic_file" ]]; then
	topic="$(cat "$topic_file")"
	echo "Existing topic found: $topic"
else
	# uuidgen may not be available on minimal Linux (Alpine, etc.) — fallback to kernel uuid
	if command -v uuidgen &>/dev/null; then
		topic="agent-vault-$(uuidgen | tr '[:upper:]' '[:lower:]')"
	else
		topic="agent-vault-$(tr '[:upper:]' '[:lower:]' </proc/sys/kernel/random/uuid)"
	fi
	echo "$topic" >"$topic_file"
	echo "Generated new topic: $topic"
fi

# ── ntfy client config ─────────────────────────────────────────────
ntfy_config_dir="$HOME/.config/ntfy"
mkdir -p "$ntfy_config_dir"
ntfy_config="$ntfy_config_dir/client.yml"

case "$platform" in
linux | macos | wsl | wsl-systemd)
	# All platforms use the toast handler script for rich notifications with icon support.
	# toast-handler.sh detects platform internally and dispatches to the correct mechanism.
	handler_path="$skill_dir/toast-handler.sh"
	notify_cmd="/bin/bash \"$handler_path\""
	;;
esac

cat >"$ntfy_config" <<EOF
# ntfy client configuration — generated by vault-triage setup.sh
# Topic: $topic
# Platform: $platform

default-host: https://ntfy.sh
subscribe:
  - topic: $topic
    command: $notify_cmd
EOF

echo "Wrote ntfy client config to $ntfy_config"

# ── Scheduled timers for daily summaries ────────────────────────────
config_dir="$(cd "$skill_dir/../.." && pwd)"
dashboard_cmd="/bin/bash \"$config_dir/tools/triage-dashboard.sh\" --notify-summary"

case "$platform" in
linux | wsl-systemd)
	# systemd user timers
	unit_dir="$HOME/.config/systemd/user"
	mkdir -p "$unit_dir"

	cat >"$unit_dir/vault-triage-summary.service" <<UNIT
[Unit]
Description=Vault triage summary notification

[Service]
Type=oneshot
Environment=AGENT_VAULT=$vault
Environment=NTFY_TOPIC=$topic
ExecStart=$dashboard_cmd
UNIT

	cat >"$unit_dir/vault-triage-summary.timer" <<UNIT
[Unit]
Description=Daily triage summary notifications (9am and 5pm)

[Timer]
OnCalendar=*-*-* 09:00:00
OnCalendar=*-*-* 17:00:00
Persistent=true

[Install]
WantedBy=timers.target
UNIT

	systemctl --user daemon-reload
	systemctl --user enable --now vault-triage-summary.timer 2>/dev/null || {
		echo "Warning: could not enable timer. Run manually:"
		echo "  systemctl --user enable --now vault-triage-summary.timer"
	}
	echo "Installed systemd user timer for daily summaries (9am, 5pm)"
	;;

macos)
	# launchd plist
	plist_dir="$HOME/Library/LaunchAgents"
	mkdir -p "$plist_dir"
	plist="$plist_dir/com.agent-vault.triage-summary.plist"

	cat >"$plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.agent-vault.triage-summary</string>
    <key>ProgramArguments</key>
    <array>
        <string>bash</string>
        <string>$config_dir/tools/triage-dashboard.sh</string>
        <string>--notify-summary</string>
    </array>
    <key>EnvironmentVariables</key>
    <dict>
        <key>AGENT_VAULT</key>
        <string>$vault</string>
        <key>NTFY_TOPIC</key>
        <string>$topic</string>
        <key>PATH</key>
        <string>/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin</string>
    </dict>
    <key>StartCalendarInterval</key>
    <array>
        <dict>
            <key>Hour</key>
            <integer>9</integer>
            <key>Minute</key>
            <integer>0</integer>
        </dict>
        <dict>
            <key>Hour</key>
            <integer>17</integer>
            <key>Minute</key>
            <integer>0</integer>
        </dict>
    </array>
</dict>
</plist>
PLIST

	# Try bootstrap (modern), fall back to load (legacy <10.11) — both are idempotent-safe here
	launchctl bootstrap "gui/$(id -u)" "$plist" 2>/dev/null ||
		launchctl load -w "$plist" 2>/dev/null ||
		{
			echo "Warning: could not load plist. Run manually:"
			echo "  launchctl bootstrap gui/\$(id -u) $plist"
		}
	echo "Installed launchd agent for daily summaries (9am, 5pm)"
	;;

wsl)
	# Windows scheduled tasks via schtasks.exe
	# Note: BurntToast PowerShell module must be installed on Windows side.
	win_script="$config_dir/tools/triage-dashboard.sh"

	schtasks.exe /Create /SC DAILY /TN "AgentVault\\TriageSummaryAM" \
		/TR "wsl.exe bash -c \"AGENT_VAULT='$vault' NTFY_TOPIC='$topic' /bin/bash '$win_script' --notify-summary\"" \
		/ST 09:00 /F 2>/dev/null || {
		echo "Warning: could not create morning task. You may need to run from an elevated prompt."
	}

	schtasks.exe /Create /SC DAILY /TN "AgentVault\\TriageSummaryPM" \
		/TR "wsl.exe bash -c \"AGENT_VAULT='$vault' NTFY_TOPIC='$topic' /bin/bash '$win_script' --notify-summary\"" \
		/ST 17:00 /F 2>/dev/null || {
		echo "Warning: could not create evening task. You may need to run from an elevated prompt."
	}
	echo "Created Windows scheduled tasks for daily summaries (9am, 5pm)"
	;;
esac

# ── Summary ─────────────────────────────────────────────────────────
echo ""
echo "=== Setup Complete ==="
echo "Platform:     $platform"
echo "Topic:        $topic"
echo "Topic file:   $topic_file"
echo "ntfy config:  $ntfy_config"
echo ""
echo "Next steps:"
echo "  1. Install the ntfy CLI if not already installed:"
echo "     - Linux:  sudo apt install ntfy  (or: pip install ntfy)"
echo "     - macOS:  brew install ntfy"
echo "     - Or just use curl (notify.sh detects which is available)"
echo "  2. Subscribe to your topic on your phone:"
echo "     - Install the ntfy app (Android/iOS)"
echo "     - Subscribe to topic: $topic"
echo "  3. Test with:"
echo "     source $config_dir/tools/notify.sh"
echo "     notify_triage escalation test/task 'Hello from setup'"
if [[ "$platform" == "wsl" || "$platform" == "wsl-systemd" ]]; then
	echo ""
	echo "  Note (WSL): Desktop notifications are dispatched via toast-handler.sh."
	echo "  For icon support, install BurntToast on Windows: Install-Module BurntToast -Scope CurrentUser"
fi
