import { tool } from "@opencode-ai/plugin";
import { mkdir, writeFile, access } from "node:fs/promises";
import path from "node:path";
import os from "node:os";

const DIRS = [
  "tasks",
  "_misc/archive/tasks",
  "_misc/archive/draft",
  "audits",
  "projects",
  "_misc/cache",
  "design",
  "draft",
  "repo-notes",
  "_misc/templates",
  "_misc/images",
] as const;

const AGENTS_MD = `# Agent Vault

## What This Repository Is

This is a **git-tracked Obsidian vault** serving as a knowledge base. It contains
reference documentation, implementation schemas, code reviews, and triage
entries — not source code. There are no build systems, tests, or linters.

## Vault Structure

### \`tasks/<owner>/<repo>/<task>/\` — Implementation tasks

Each task directory contains up to three files:
- \`schema.md\` — Actionable implementation spec that an AI agent can execute step-by-step.
- \`review.md\` — Structured code review for work done against the schema.
- \`triage.md\` — Escalation notes, design questions, and run summaries.

### \`tasks/_fleet/<task>.md\` — Fleet (cross-repo) schemas

Umbrella documents coordinating work across multiple repositories. These are
flat files (not directories) since they don't have per-task reviews or triage.

### \`repo-notes/<owner>/<repo>/\` — Repository reference documentation

Reference summaries of repository internals (build systems, architecture,
scripts). A future agent session should be able to understand a subsystem
by reading one file.

### \`design/\` — Design documents

High-level thinking: architecture explorations, trade-off analyses, roadmaps,
and cross-cutting concerns.

### \`draft/\` — Work-in-progress documents

Staging area for notes and specs under active development.

### \`_misc/\` — Infrastructure (hidden by \`_\` prefix in Obsidian)

Umbrella directory for all vault infrastructure that is not user-facing content.
Collapsed by default in the Obsidian file explorer. Contains:

- \`_misc/archive/\` — Completed work
- \`_misc/cache/\` — GitHub metadata cache
- \`_misc/templates/\` — Format templates
- \`_misc/images/\` — Notification icons and image assets

#### \`_misc/archive/\` — Completed work

Mirrors the active directories for work that has been completed:
- \`_misc/archive/tasks/\` — Completed task directories (schema + review + triage).

When asked to archive tasks, move them from the active directory into the
corresponding \`_misc/archive/\` subdirectory.

### \`audits/<owner>/<repo>/\` — Audit reports

Point-in-time quality snapshots generated by \`@auto-auditor\`. Each file is
named \`<date>-<label>.md\` (e.g. \`2026-03-29-full-audit.md\`). Multiple audits
per repo accumulate here as a historical series.

#### \`_misc/cache/\` — GitHub metadata cache

Cached project board, milestone, and label data for repositories.

### \`projects/<owner>/\` — Project status documents

Human-readable per-repo project snapshots maintained by \`@project-manager\`.
Each file (\`projects/<owner>/<repo>.md\`) mirrors the current state of open/closed
issues, milestone progress, and project board columns for a vault-managed repo.
Refreshed whenever PM performs state-changing operations or is explicitly asked
to sync. Use \`backend: github\` for GitHub-backed projects and \`backend: local\`
for vault-only tracking.

### Other

- \`.obsidian/\` — Obsidian configuration (do not modify).
- \`AGENTS.md\` — This file.
- \`triage-inbox.md\` — Generated triage dashboard (run \`vault-triage\` skill to refresh).
- \`_misc/templates/\` — Format templates for schemas, reviews, triage, and issues.
- \`_misc/images/\` — Notification icons and other image assets.

## Workflow

All non-trivial implementation work follows three phases:

1. **Plan** — \`@planner\` explores the codebase, discusses with the user, writes
   a schema to \`tasks/<owner>/<repo>/<task>/schema.md\`.
2. **Implement** — \`@implementor\` or \`@auto-implementor\` executes the schema
   step-by-step, committing after each group.
3. **Review** — \`@reviewer\` writes a structured review to
   \`tasks/<owner>/<repo>/<task>/review.md\`.

## Agent Roles

| Agent | Role |
|-------|------|
| \`@planner\` | Schema authoring, GitHub issue creation |
| \`@project-manager\` | Issue lifecycle, project board ops, milestone management, vault project status |
| \`@implementor\` | Manual schema execution with approval gates |
| \`@auto-implementor\` | Autonomous schema execution with bounded review loop |
| \`@reviewer\` | Structured code review |
| \`@designer\` | Repo notes, design documents, drafts |
| \`@auto-auditor\` | Headless audit agent — tool detection, static analysis, vault report |

## Environment

| Variable | Purpose |
|----------|---------|
| \`AGENT_VAULT\` | Path to this vault (e.g. \`~/obsidian/agent.obs\`) |
| \`AGENT_REPOS\` | Path to local repository checkouts (e.g. \`~/repos\`) |

## Conventions

- Documents are Markdown, authored for Obsidian (may use wiki-links, callouts).
- Do not hard-wrap prose — Obsidian soft-wraps paragraphs.
- Schemas and reviews use YAML frontmatter for metadata (\`repo\`, \`status\`, \`date\`, etc.).
- Path convention: \`tasks/<owner>/<repo>/\` mirrors the local checkout path
  convention \`~/repos/<owner>/<repo>\`.
- Agents access vault files directly via standard filesystem tools (Read, Write, Edit,
  \`find\`, \`rg\`). Frontmatter is managed via the \`fm_read\`/\`fm_write\` tools.
- **Task and issue titles must not contain regex special characters** (\`.\`, \`(\`, \`)\`,
  \`*\`, \`[\`, \`]\`, \`+\`, \`?\`, \`{\`, \`}\`, \`^\`, \`$\`, \`|\`, \`\\\`). The \`vault-lint\` script
  uses title text as a regex pattern when scanning review files — special characters
  will silently corrupt issue-block extraction.
`;

export default tool({
  description:
    "Initialize or verify the agent vault directory structure. " +
    "Creates all directories and copies templates without overwriting " +
    "existing files. Idempotent — safe to run multiple times.",
  args: {
    vault_path: tool.schema
      .string()
      .optional()
      .describe("Path to the vault directory (default: $AGENT_VAULT)"),
  },
  async execute(args) {
    // 1. Resolve vault path
    let vault = args.vault_path ?? process.env.AGENT_VAULT ?? "";
    if (!vault) {
      return "Error: vault_path not provided and AGENT_VAULT is not set.";
    }

    // Expand leading ~
    if (vault === "~") {
      vault = os.homedir();
    } else if (vault.startsWith("~/")) {
      vault = path.join(os.homedir(), vault.slice(2));
    }

    const createdPaths: string[] = [];

    // Ensure vault root exists (always, not counted)
    await mkdir(vault, { recursive: true });

    // Helper: create a directory only if it doesn't already exist; track if created
    async function ensureDir(rel: string): Promise<void> {
      const full = path.join(vault, rel);
      try {
        await access(full);
        // Already exists — skip
      } catch {
        await mkdir(full, { recursive: true });
        createdPaths.push(rel);
      }
    }

    // Helper: write a file only if it doesn't already exist; track if created
    async function ensureFile(rel: string, content: string): Promise<void> {
      const full = path.join(vault, rel);
      try {
        await access(full);
        // Already exists — skip
      } catch {
        await writeFile(full, content, "utf-8");
        createdPaths.push(rel);
      }
    }

    // 2. Create all directories
    for (const dir of DIRS) {
      await ensureDir(dir);
    }

    // 3. Write AGENTS.md if missing
    await ensureFile("AGENTS.md", AGENTS_MD);

    // 4. Build output
    const header = `Initializing vault at: ${vault}`;

    if (createdPaths.length === 0) {
      return `${header}\n\nDone: vault already fully initialized.\nVault path: ${vault}`;
    }

    const lines = createdPaths.map((p) => `  created: ${p}`).join("\n");
    return `${header}\n\n${lines}\n\nDone: ${createdPaths.length} items created.\nVault path: ${vault}`;
  },
});
